// Plugins required for the Android application
plugins {

    // Android Application Plugin
    // Enables Android app development features such as APK generation,
    // build variants, signing, packaging, etc.
    id("com.android.application")

    // Flutter Gradle Plugin
    // Connects Flutter with Android's Gradle build system.
    // Must be applied after Android and Kotlin plugins.
    id("dev.flutter.flutter-gradle-plugin")

    // Google Services Plugin
    // Required for Firebase integration.
    // Processes the google-services.json file and configures Firebase services.
    id("com.google.gms.google-services")
}

android {

    // Unique namespace used by Android for generated code (R class, BuildConfig, etc.)
    namespace = "com.example.visionsos"

    // Android SDK version used to compile the application.
    // Flutter automatically provides the version.
    compileSdk = flutter.compileSdkVersion

    // Native Development Kit (NDK) version used for native code support.
    ndkVersion = flutter.ndkVersion

    // Java compiler configuration
    compileOptions {

        // Source code compatibility version
        sourceCompatibility = JavaVersion.VERSION_17

        // Generated bytecode compatibility version
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {

        // Unique application identifier.
        // This identifies your app on devices and Google Play Store.
        applicationId = "com.example.visionsos"

        // Minimum Android version supported by the application.
        // Users with lower versions cannot install the app.
        minSdk = flutter.minSdkVersion

        // Target Android version the application is optimized for.
        targetSdk = flutter.targetSdkVersion

        // Internal version number used for updates.
        // Must increase for every Play Store update.
        versionCode = flutter.versionCode

        // User-visible version name.
        // Example: 1.0.0, 1.1.0, 2.0.0
        versionName = flutter.versionName
    }

    // Build configurations
    buildTypes {

        // Release build settings
        release {

            // Signing configuration for release APK/AAB.
            // Currently using debug signing keys for testing.
            // Replace with your production keystore before Play Store publishing.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

// Kotlin compiler settings
kotlin {

    // Compiler-specific options
    compilerOptions {

        // JVM target version for Kotlin bytecode generation.
        // Ensures Kotlin compiles to Java 17 compatible bytecode.
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

// Flutter-specific configuration
flutter {

    // Path to Flutter project root directory
    // "../.." means move two levels up from the Android folder.
    source = "../.."
}
